# Generated by Django 3.0.1 on 2019-12-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sex', models.TextField()),
                ('school', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
