# Generated by Django 3.0.1 on 2019-12-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191221_0822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello1',
        ),
    ]
